export const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE';
export const UPDATE_DATE_TYPE = 'UPDATE_DATE_TYPE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const SET_COLOR_THEME = 'SET_COLOR_THEME';
export const SET_WHETHER_OCCUPY_NEWTAB = 'SET_WHETHER_OCCUPY_NEWTAB';
